[package]
name = "tigerust"
version = "0.1.0"
authors = ["ielvert-menlo <ielvert@menlo-technologies.com>", "QPotato <federicobadaloni@hotmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
lalrpop-util = "0.17.1"
regex = "0.2.0"
